server:
  port: 8081
app:
  name: spring-ai
spring:
  ai:
    ollama:
      base-url: http://103.242.3.252:11434
      chat:
        options:
          model: llama3
          num-batch: 20000
          temperature: 0.7


